#+title:em Suite
#+author:jthulhu

* em Suite
The em Suite, stylized MS, is a personal information manager.  It features the following components
  - a calendar manager
  - a mail client
  - a ledger
  - a matrix client
  - a contact manager

It is built out of the frustration I have when trying to use existing software to do these tasks.
MS is built with the following constaints:
 - No JS, and minimal web technologies.  It is now standard for emails to expect that the client
   is able to perform HTML rendering, and MS can't go against that.  However, that is the only
   part of the whole suite where any web technology is used.  Web technologies are to be used for
   websites, and that's it.
 - No plain-text storage or communication.  MS will refuse to proceed if it can't store data and
   communicate *exclusively* in an encrypted fashion.  Non-encrypted storage backends are not even
   implemented, and will never be.
 - Integration with the OS secret facilities.  MS will refuse to proceed if it can't interface
   with your password manager to fetch passwords, and with the OS secret service to store
   encryption keys.  *You will never be asked to fill in data*.
 - Fully declarative.  MS does not support imperative-style configuration.  For instance, the *only*
   way to add accounts is to declare them into a configuration file.  There is no "create a new
   account" button.  Beware, *if you delete an account from the configuration file, all data
   corresponding to that account will be wiped*. Similarly, if you add an account to the
   configuration file, MS will automatically fetch sensitive information (such as passwords) and
   update its database.  *MS' state is entirely controleld by its configuration file*.  This makes
   managing MS via Nix a first-class feature, not an afterthought.
 - Incremental work only.  MS will always to its work incrementally.  This means that, if you have
   fetched calendar data, that data will not be refetched unless the server wants it.
 - Keyboard-driven interface.  MS aims at having a nice. modern-looking graphical interface
   without forcing the user to use their mouse.
 - Transparent.  MS' errors and misbehaviours should be easily inspectable, to prevent frustration
   when something is not working.
 - Compatible with Tuta.  Tuta is the email provider I use.  Unfortunately, its client doesn't fit
   my needs, and has no public documentation on how to use their non-standard API.
 - *No LLMs*.  All the code is hand-written by me.

This README serves both as a description of what this project does, but also a centralized
documentation.  Implementing MS required learning various standards, raised questions about them.
I keep here all that high-level information, to avoid having to search again for that
information, and also to keep track of implementation decisions that have been made.

*Beware*: Information in this document is not necessarily true!  I might have misunderstood or
overlooked things.  Information is more likely to be true if it's well documented on the internet.

** Features
 - [1/2] Calendar
   - [X] User Interface
     - [X] Infinite scrolling view
     - [X] Day view
     - [X] Month view
   - [-] Synchronization
     - [X] Fetching data from remote
     - [ ] Establishing a push notification system
     - [ ] Pushing data to remote
 - [0/2] Email
   - [ ] User interface
   - [ ] Tuta
   - [ ] Standard email accounts
     - [ ] Database
       - [ ] Full text search
     - [ ] Synchronization
       - [ ] Incremental synchronization
       - [ ] Push notifications

* Implementation choices
** User interface library
I have chosen ~iced~, mainly because it boasts lot's of cool-sounding features, and because it has
a strong ecosystem.  On the filp side, ~iced~ has basically no good documentation.

This structures the rest of the application, because ~iced~ uses an ~async~ based task system.
Hence, all subsequent library choices have to take into account the ~async~ nature of the
application.

*** ~iced~ modularisation
To modularize the UI, we use the suggested workflow.  A module is composed of a type satisfying
the following pseudo-trait
#+begin_src rust
  trait Module {
      type InMessage;
      type UpMessage;

      fn new() -> (Self, Task<OutMessage<Self::InMessage, Self::UpMessage>>);
      
      async fn view(&self, ...) -> Element<'_, OutMessage<Self::InMessage, Self::UpMessage>>;
      
      async fn update(&mut self, message: InMessage, ...) -> Task<OutMessage<Self::InMessage, Self::UpMessage>>;
  }
#+end_src
where ~OutMessage<In, Up>~ is the sum of ~In~ and ~Up~.  Basically, it looks like ~iced~ modules, except
that the "output message" is not the same type as the "input message", with the idea that you can
either send messages to yourself (called the ~InMessage~), or send the messages upwards (the
~UpMessage~).  The caller module has to deal with ~UpMessage~, and pass through the ~InMessage~.

Both ~view~ and ~update~ methods are ~async~, but not the ~new~ associated function, because the module
has to be initialized to initialize the UI, and the UI has to be initialized /before/ the ~iced~
async runtime is started.  If the module requires ~async~ initialization, there are two cases:
 - either the initialization is expected to be fast, in which case you can just
   ~futures::executor::block_on~: have the thread just wait for the asynchronous code finish;
 - or, your module must have a state that encodes yet-to-be initialized data, and start a ~Task~
   that runs the initialization code, and modify the state when initialized.  This entails that
   the ~view~ method must be able to represent the yet-to-be initialized application.
The first option should only be used if it introduces a delay that is not noticeable to the user!
We want to keep the application as snappy as possible.

** ~async~ runtime backend
~iced~ restricts the available runtime backends.  I have chosen the ~tokio~ implementation, with
several threads.

I've chosen ~tokio~ because it works well with other libraries, such as ~sqlx~, which further entails
several threads.

** Database backend
I looked at several options for the database backend:
 - ~rusqlite~: bindings to ~sqlite~.  Rejected because:
   - it doesn't work well with ~async~ code
 - ~diesel~: fully-featured ORM.  Rejected because:
   - I've tried it before, and I don't really like its migration management
   - it doesn't support natively ~async~ (even though there seems to be ~diesel-async~, a drop-in
     replacement that makes ~diesel~ async)
 - ~limbo~: a rewrite or ~sqlite~ in pure Rust, with ~async~ first.  Very interesting, because the C
   SQLite implementation doesn't utilize Linux' asynchronous features for fs IO, while ~limbo~
   does.  Rejected because:
   - ~limbo~ doesn't seem to feature on-disk encryption, yet.  It has some experimental features,
     but that didn't seem mature enough.  This could change quickly though.
 - ~sqlx~: a middle-level SQL library.  It's not an ORM, but is also higher-level than plain sqlite
   bindings.  Accepted because
   - it's ~async~-first (even though it still relies on the C SQLite, which doesn't utilize Linux'
     fs IO async operations).
   - a gotcha of ~sqlx~ with sqlcipher encryption is that this prevents ~sqlx~ from checking SQL
     statements, because ~sqlx~ tries to connect to a /real/ database at dev time, and does so
     without unencrypting the database.
 - ~sea-orm~: A fully featured ORM, akin to Diesel, but more recent and less widely used.  Accepted because
   - it's async first
   - can use ~sqlx~
   - has an interesting active model workflow: rather than manually specifing what data should be
     included, you handle data with extra logic.  When you "save" the data, it does some
     introspection to update only the data that has changed.
   - is capable of checking queries without relying on ~sqlx~
   - has an entity-first workflow: this means that you write Rust code, and that dictates how
     your database is managed.  This is opposed to writing SQL declarations, and having Rust data
     generated.  Not only I dislike the idea of generating Rust data, and I also prefer writing
     Rust over SQL, but interacting with "real" SQL works poorly with encrypted databases.  The
     downside is that I have to manage migrations "by hand", in the sense that not only I have to
     declare what the data look like, but I also have to write the code that generates the
     database schema that matches.  This /has/ to be written twice, because the data matches only
     the latest version of the database's schema, whereas migrations have to manage versions of
     the schema: if the schema doesn't have the latest schema, we have to run migrations to make
     it so.

** Tuta backend
Tuta doesn't have an officially supported library.  There are three Rust libraries related to Tuta
 - ~tuta_poll~: it speaks to Tuta over the web directly, using an undeclared API.  This looks cool,
   and documented, but doesn't have enough features: it can basically:
   - fetch data
   - set read status
 - ~tutabridge~: it's not really a library, rather an application that translates the Tuta API into
   standard IMAP/SMTP API.
   - I think it's (at least partially) LLM generated.
   - It doesn't have any kind of documentation :'(
   - it relies on the Tuta SDK, but actually on a forked version with extra patches, whereas I
     want to depend on the upstream Tuta SDK, to
     - avoid having client version mismatch
     - have the latest security fixes directly
   - I want to make a "native" Tuta library, which eventually has to support lots of features
 - ~tuta-sdk~: it's a library, but it's not even published on ~crates.io~.  Instead, one has to
   depend directly on their git repository.  Furthermore, it's not documented at all, there are
   no examples.
We try to write a native client depending directly on ~tuta-sdk~, but so far I haven't managed
performing a login flow yet.

The ~tuta-sdk~ handles on-disk encrypted data natively.  This means that ~tuta-sdk~ asks you to offer
a key/value storage implementation, and will use that to store an encrypted database, including
text indexes for full-text search, or things alike.  Hence, it would be a bad choice to store
these key/value pairs inside a database: we would have a database inside a database, leading to
useless performance penalties.

Hence, we choose to write this data directly in files, each key being a path to the file with the
data.  Because we want to avoid IO blocking operations within an ~async~ runtime, we could either
perform these operations on dedicated threads (for instance using ~tokio::spawn_blocking~).
However, disk operations are more likely to be IO bound than CPU bound, and thus, it seems a good
fit for a native async implementation.  This is possible using Linux async fs features.

** Keyring backend
I'm not sure whether there exist alternatives to the ~oo7~ crate, but since this one does all I
need and is ~async~ first, I've opted for it.

** WebDAV backend
I want to have my calendars and contacts handled by a Nextcloud instance, through a CalDAV and
CardDAV API.  CalDAV and CardDAV are specialized WebDAV standards, in the sense that they define
a protocol that relies on the WebDAV protocol to exchange data between the client and the server.

There are several WebDAV, and even CalDAV or CardDAV clients:
 - ~libdav~: a robust and exhaustive implementation of CalDAV and CardDAV.  Rejected because:
   - ~fast-dav-rs~ seems more efficient (I'm not sure efficiency here is really a problem, but why
     not get faster libraries...)
 - ~minicaldav~: a lightweight implementation.  Rejected because:
   - it's not ~async~-first.
 - ~fast-dav-rs~: a streaming, fast implementation.  Accepted because
   - it's ~async~-first
   - it supports modern features to handle large datasets, such as:
     - incremental sync
     - batch operations
     - streaming results
     I'm not sure this is useful yet, but it's nice to have a library that can easily scale if
     this becomes necessary.
 - ~io-webdav~:  similar to ~fast-dav-rs~.  Rejected because:
   - I don't have reasons to choose one of ~io-webdav~ or ~fast-dav-rs~ over the other, because they
     look very similar.
 - ~aimcal-caldav~: seems to bundle many more features, including WebDAV client.  For instance, AI
   support, and stuff like that.  Rejected because:
   - it does too much, I want to have finer control
 
** Password store backend
I'm not sure whether there exists a generic password manager API.  Since I use GNU Pass, I only
looked at libraries that can handle that.
 - ~libpass~: a native Rust implementation of GNU Pass.  It's not as fully-featured as GNU Pass,
   but it does all I need.  Accepted because:
   - it's ~async~-first
   - it can easily read passwords from the store

I don't know whether other libraries exists, but this one does what I need, so I haven't looked
further.

** push-notification backend
Push notification is a synchronization strategy that is supposed to more efficient than the naive
one.

The naive approach is to have one or both of:
 - user-triggered synchronization.  It's good to have them, but it's annoying because one ends up
   refreshing again and again, or missing notifications.
 - polling, that is, performing synchronization periodically.  This is a bad solution because:
   - it consumes more resources, including battery.  If every application that required
     synchronizing data used polling, battery usage would be much higher.  See what Android does.
   - it introduces lattency for the user, which is (very) annoying.

The good way to handle this is to have the server notify us when we have to do some
synchronization.  If the setup is properly done, the delay between the event being receiving by
the server and the user seeing the event being applied in the interface should be at most tens or
hundreds of milliseconds.

However, this still consumes a significant of battery, because each application has to keep a
connection alive, which is not an entirely passive operation (passive in the sense that it
doesn't consume resources when nothing happens).  To optimize this further, we can ask a
/notification server/ to open all these connections, have all applications of our system create a
/single/ connection to that server, and then some OS service is in charge of dispatching
notifications to applications to which they belong.  This is precisely the role of the
UnifiedPush standard.  It's a standard that handles specifies both the API that a notification
server should expose, and the OS service API.

For instance, Nextcloud can offer a UnifiedPush service, to be used coupled with Nextcloud
authentication.

For the OS side, KDE has implemented a OS service that respects the API, called
~kunifiedpush-provider~.  It doesn't have to be installed alongside KDE, it can be used as a
standalone UP provider.  It is, as far as I know, the only such implementation.

Note that Nextcloud WebDAV implements a WebDAV Push API, which is compatible with Unified Push.

*** Unified Push backends
Unified Push has an official Rust implementation, called ~unifiedpush-rs~.  I'm not aware of
alternatives.

However, ~unifiedpush-rs~ requires a storage backend, to store the application side state of the
Unified Push implementation (such as which distributor to use).  Because I don't want to store
any data un-encrypted on-disk, I have to implement one that encrypts data.

** iCalendar backend
CalDAV is a transport protocol, that transports iCalendar data, which is the support that
actually contains relevant data for the application.

This means that we need an iCalendar parser.  However, iCalendar having some... complexities, it
also require a library that generates occurrences out of iCalendar data.  These two operations
are not necessarily performed by the same library.

- ~ical~: a robust library for parsing iCalendar entries.
- ~calcard~: a robust library for parsing iCalendar and vCard entries.
- ~icalendar~: again, a robust library for parsing iCalendar entries.
- ~rrule~: a library for generating occurrences out of an iCalendar event
- ~rrules~: a library for generating occurrences out of an iCalendar event

I have to say... most of these libraries are very similar.  ~icalendar~ offers a slightly higher
level API, and also offers integration with ~rrule~ to have access to its features via the same
~icalendar~ API.  Because of this conveniences, I chose ~icalendar~ / ~rrule~ combination.

** ~async~ filesystem operations backend
Linux offers async the IO interface ~io_uring~.

 - ~io-uring~: low-level bindings to Linux' ~io_uring~.  Rejected because:
   - it's too low-level
 - ~tokio-uring~: higher-level bindings, with ~tokio~ integration.  Accepted because:
   - lack of alternatives
   - does what I need

** UI ceache backend
The architecture of the application is to have the UI state contain a cache of the data, and a
database containing the actual data.  When the UI requires some information (such as: "what are
the events happening on this day?"), we don't want it to fetch it in the database directly,
because that would make the UI sluggy.  Instead, it asks a background process to fetch that data,
and fill in UI's cache.  The UI only reads the cache to show information.

We want the cache to implement cache unloading on its own (that is, the cache should forget about
information that is no longer useful to the UI on its own, without the UI explicitely specifying
which data it doesn't need anymore).  It also has to be capable of accepting writes from the
background process, while there are reads from the UI.

I haven't looked a lot at alternatives to ~moka~, because ~moka~ has all the features required.  Note
that we do not use the ~async~ version of ~moka~ on purpose, because reads *must not* be asynchronous:
UI drawing must be immediate!

This entails that writes are blocking, which could be counter-productive.  However, in practice,
writes are fast, so we don't need to offload the writes on another thread.

** Mail parser backend
The plain email format is annoying to store in a database, because it encodes a nested data
structure.  ~mail-parser~ is capable of flattening that structure, exposing:
 - headers
 - mail content, in different formats (plain text, HTML, ...)
 - attachments

** HTML renderer backend
A simple HTML render has to be used, to render emails, compatible with iced.

 - ~iced_webview~: an ~iced~ widget based on Ultralight or Webkit.  Rejected because
   - Ultralight is proprietary
   - Webkit is /waaaaayyyyy/ overkill, we want to render static HTML with basic CSS support
   - I'm not sure it's possible to capture resource resolution
 - ~iced_webview_v2~: an ~iced~ widget supporting several backends

* Specs
All data is stored in SQLite databases, fully encrypted with SQLcipher.  This means that every
connection must, when established, specify the encryption key.

The encryption key itself is stored in the OS keyring.  If the OS has no keyring backend, then
the process should just fail.  There is no safe way to recover, because then there is no way to
store secrets fully encrypted on disk.

By default, we do not use a special ~id~ auto-incremented primary key.  Instead, we make the
primary key the data that actually uniquely identifies data.  Using SQLite as backend, it's not
much of an overhead, and this helps keeping the table data close to the real world constraints.

The main exception is when we need to have recursive data.  For instance, when we store a ~folder~
data, it has to reference its parent, and we can't do that without an internal ~id~.

** Code overview
The whole configuration, which is very important because it drives the state of the application,
is present in ~src/config.rs~.

** Calendar
A CalDAV server can serve multiple calendars, each with their own ~href~, which acts as a unique
ID.  A calendar itself is composed of several objects, which are served indipendently.  If we
think of the calendar as a directory, objects would be ~ics~ files within the directory.  Each
object typically defines one or more events.  Events typically define one or more occurrence.

Each object must have exactly one, unique event ~UID~ used throughout all events defined in it.
Within an object, events can either
- simple events: events with a single occurrence;
- recurring events: events with a recurrence rule to generate all its occurrences;
- exception events: modifications to recurrence rules found in an other recurring event *in the same object*.

Hence, to generate all occurrences, one must:
- handle each object separatly
- for each /main event/ (ie. one that generates occurrences),  generate all of its occurrences
- for each /exception event/, correct the generated events

*** Incremental synchronization
Incremental synchronization for CalDAV works as follows.  Whenever we make a request, if the
server implements incremental synchronization (modern implementations, such as Nextcloud, do), it
returns a ~sync_token~ which represents a timestamp.  Basically, you have received all the data as
it exists on the server, up to the timestamp represented by the ~sync_token~.  Conversely, when we
make a request, we can also include a ~sync_token~, and the server will only include modifications
since that timestamp.

Exceptionnaly, if the server has restructured its internal data, or if it has deleted the data
required to compute the delta given a ~sync_token~ (which can happen if you don't use that token
for a long time, or if there are too many tokens issued by the server), the server can indicate
to you that it will give you the /full/ data, asking you to forget local data and reset to what the
server just sent you.

Keep in mind that incremental synchronization happens at the /calendar/ level.  Each level has a
token.  Hence, performing an incremental synchronization for a given user will involve several
incremental synchronizations, one for each calendar.

*** FAQ
- Is it possible for a recurrent event, and for some associated exceptions, to have different
  datetime kinds?

  No, the exception event datetime should have the *same* timezone and type as its associated event.
- Is it possible for two events in different objects to interfere with each other?

  No, an exception event can only affect events defined in the same object.

** Email
Email works with two main protocols: IMAP and SMTP.

IMAP has the purpose of exposing a filesystem-like interface, exposing the remote storage of
emails.  The IMAP standard is built around capabilities, that is, features that the server
supports.

SMTP, on the other hand, serves as a protocol for exchanging emails.  Note that, as an email
client, we don't need to care about how an email is received: the server handles that, and stores
them, which can then be queried via IMAP.

However, I've realized later that IMAP is an old, broken protocol.  For instance, even "modern"
support for push notifications:
 - do not support UnifiedPush
 - permit only to listen for modifications on a *single directory* at a time

Here is a more complete comparison matrix of features that are especially relevant to me.  There
are other differences, usch as JMAP using JSON format for payload, whereas the IMAP protocol is a
custom, command-based format, making JMAP easier to implement, but since I use libraries for
both, it doesn't affect me.

| Feature            | *IMAP*                                      | *JMAP*                 |
|--------------------+-------------------------------------------+----------------------|
| *Push notifications* | Not always supported, only per-directory  | Per account, with UP |
| *Session state*      | Stateful                                  | Stateless            |
| *Can send emails*    | No, requires SMTP                         | Yes                  |
| *Used ports*         | 143 or 993                                | 443 (HTTPS)          |
| *Can move emails*    | Not natively, introduces a lot of re-sync | Yes                  |
| *Batch operations*   | No                                        | Yes                  |
| *Bandwidth usage*[fn:1]  | Medium                                    | Low                  |
| *Threads*            | Not commonly supported                    | Built-in             |
| *Tags*               | No                                        | Yes                  |

For these reasons, I'm switching to an  email provider that supports JMAP.

[fn:1] See https://jmap.io/why-jmap/#better-performance.

*** IMAP spec
Note that this section is outdated, I know focus only on the JMAP protocol.

**** IMAP Capabilities
The IMAP protocol functions by sending plain text commands over a session.  It is important to
note that the IMAP protocol is /stateful/: a session is first established, including login.  Each
command starts with a command identifier, any string that is used for the server to signal which
command it responds to.

Email servers disclose "capabilities", that is, features of the standard they support.  Here is a
quick reminder of relevant capabilities
 - ~ID~: this capability permits sending software information, mainly for debugging and telemetry.
 - ~IDLE~: this capability offers an similarly named command, that waits for extra data to arrive.
   This is a very efficient push notification system.
 - ~SPECIAL-USE~: allows the server to tag special directories, like, which directory is the
   "Trash" directory, regardless of the actual name of the directory.
 - ~CONDSTORE~ and ~QRESYNC~: the ~CONDSTORE~ capability allows the client to ask for a timestamp for
   each folder.  This timestamp represents the date up to which the data stored by the client is
   in sync.  On the other hand, ~QRESYNC~ allows the client to ask "what happened since a given
   moment", where the moment is encoded by the token provided by ~CONDSTORE~.  This permits
   efficient, incremental synchronization.
 - ~QUOTA~: allows the server to disclose how much space is available on the server, and the total
   space allocated for the user.  This is mainly a UI feature.
 - ~CHILDREN~: allows the server to disclose whether a directory has children directories without
   the user having to query for them.
 - ~NAMESPACE~: the folders on the server might belong entirely to the user, to someone else, or be
   shared.  This capability allows the client to understand which folders are in which category.

There list is far from being exhaustive, but lot's of capabilities are not relevant for the end
user.  We're talking about how to perform the login flow, how to improve the communication, etc.
Many features are also useful to ask the server to perform a query.  MS will not use this
feature, as we prefer synchronizing data locally, and running the query on local data.

Dovecot, a free and open source IMAP server implementation, supports all of the above
capabilities.  Therefore, we can reasonably expect all servers to implement them, and avoid
burdening ourselves with "compatibility".
 
**** Incremental synchronization
Email has a stateful incremental synchronization.  This means that you don't add to
synchronization requests some information that allows the user to send only delta information.

Instead, you have to add some information to the current /session/, and then make the sync requests
throught that session.

*** JMAP spec
One important aspect of JMAP is that it separates the synchronization of the folder structure,
and of emails.  This results in two synchronization tokens, one for the folder structure, one for
emails.

**** Folder roles
The JMAP server might assign to certain directories a role, which is simply a string supposedly
meant to represent the purpose of the directory, regardless of its name.  The standardized roles
are:
 - ~inbox~ where emails arrive when received
 - ~drafts~ where emails are stored while being written
 - ~outbox~ where emails finished, but still in the sent queue, are stored
 - ~sent~ sent emails
 - ~trash~ trashed emails
 - ~archive~ supposedly, emails that have been "processed" by the user
 - ~junk~ emails that were (manually or automatically) marked as uninteresting or malicious

Note that a single role might be assigned to several directories, except for ~inbox~, ~outbox~ and
~drafts~.

*** Database specification
**** JMAP account
The ~jmap_account~ table is:
 - ~email : Text~, which uniquely identifies an email account
 - ~provider : Text~, the URL of the email provider
 - ~password : Text~, the password of the account
 - ~folder_token : Text~ a synchronization token for the folder structure
 - ~email_token : Text~ a synchronization token for the emails

Constraints:
 - the ~email~ is a primary key

**** JMAP folder
The ~jmap_folder~ table is:
 - ~account_id : Text~, the id of the account this folders lives in
 - ~id : Text~, a unique identifier *given by the server*
 - ~parent_id : Text?~ the id of the parent directory, if any
 - ~name : Text~ the user-facing name of the directory
 - ~role : Text?~ the "role" of the directory, null if the directory has no roles
   
Constraints:
 - ~(account_id, id)~ is the primary key
 - ~account_id~ is a foreign key mapping to ~email~ of ~email_account~
 - ~(account_id, parent_id)~ is a foreign key mapping to ~(account_id, id)~ of ~email_folder~

Indexes:
 - ~index-folder-account~:
   - ~account_id~
 - ~index-folder-parent~:
   - ~account_id~
   - ~parent_id~
 
Email folders have an ~id~ because they encode a recursive tree structure.

**** JMAP email
The ~jmap_email~ table is:
 - ~account_id : Text~, the id of the account this folders lives in
 - ~id : Text~, a unique identifier *given by the server*
 - ~raw_id : Text~, a reference to the raw MIME data stored by the server
 - ~thread_id : Text~, a thread identifier generated by the server, permitting to group emails by
   thread
 - ~subject : Text?~, the subject of the email
 - ~preview : Text~ a preview generated by the server
 - ~received_at : Integer~ the UNIX timestamp of the moment the email was received
 - ~sent_at : Integer?~ the UNIX timestamp of the moment the email was sent, if the sender included
   that information

Constraints:
 - ~(account_id, id)~ is the primary key
 - ~account_id~ is a foreign key mapping to ~email~ of ~jmap_account~

Indexes:
 - ~index-email-account~
   - ~account_id~
 
**** JMAP Email in folder
The ~jmap_email_in_folder~ table is:
 - ~account_id : Text~, the id of the account
 - ~folder_id : Text~, the id of the folder
 - ~email_id : Text~ the id of the email

Constraints:
 - ~(account_id, folder_id, email_id)~ primary key
 - ~(account_id, folder_id)~ is a foreign key to ~(account_id, id)~ in ~jmap_folder~
 - ~(account_id, email_id)~ is a foreign key to ~(account_id, id)~ in ~jmap_email~

Indexes:
 - ~index-email_in_folder-folder~:
   - ~account_id~
   - ~folder_id~
 - ~index-email_in_folder-email~:
   - ~account_id~
   - ~email_id~
 
**** JMAP Email has keyword in folder
Keywords (also called /tags/ or /labels/) are, in JMAP, not stored /per email/, but /per email in a
directory/.  This means that an email can have a different set of tags, when seen in different
directories.

The ~jmap_email_in_folder_has_keyword~ table is:
 - ~account_id : Text~, the id of the account
 - ~email_id : Text~, the id of the email
 - ~folder_id : Text~, the id of the folder
 - ~keyword : Text~, the keyword

Constraints:
 - ~(account_id, email_id, folder_id, keyword)~ primary key
 - ~(account_id, email_id, folder_id)~ is a foreign key to ~(account_id, email_id, folder_id)~ in ~jmap_email_in_folder~

Indexes:
 - ~index-email_has_keyword_in_folder-email_in_folder~:
   - ~account_id~
   - ~email_id~
   - ~folder_id~

**** JMAP Email has address
This table records the headers that an email can have.  JMAP only stores
 - ~from~
 - ~to~
 - ~cc~
 - ~bcc~
as headers, and each of those has, attached, an address, which is an email address with optionally a display name
   
The ~jmap_email_has_address~ table is:
 - ~account_id : Text~, the id of the account
 - ~email_id : Text~, the id of the email
 - ~type : Text~, one of the headers listed above
 - ~display_name : Text?~, an optional better way to display an address
 - ~email_address : Text~ the email address
 - ~position : Integer~ the order in which this entry occurs

Contraints:
 - ~(account_id, email_id, type, position)~ primary key
 - ~(account_id, email_id)~ is a foreign key to ~(account_id, id)~ in ~jmap_email~

Indexes:
 - ~index-email_has_address-email~:
   - ~account_id~
   - ~email_id~
 
**** JMAP Email content
The ~jmap_email_content~ table is:
 - ~account_id : Text~, the id of the account
 - ~email_id : Text~, the id of the email
 - ~text_content : Text?~, the plain-text version of the email
 - ~html_content : Text?~, the HTML version of the email

Contraints:
 - ~(account_id, email_id)~ primary key
 - ~(account_id, email_id)~ foreign key to ~(account_id, id)~ in ~jmap_email~
   No index for this foreign key is required, as it matches the primary key.

Indexes:
 
**** JMAP Email attachment
The ~jmap_email_attachment~ table is:
 - ~account_id : Text~, the id of the account
 - ~email_id : Text~, the id of the email
 - ~id : Text~, the id of the attachment
 - ~name : Text?~, the name of the attachment
 - ~mime_type : Text~ the MIME type of the attachment
 - ~size : Integer~, the byte size of the file

Constraints:
 - ~(account_id, email_id, id)~ primary key
 - ~(account_id, email_id)~ is a foreign key to ~(account_id, id)~ in ~jmap_email~

Indexes:
 - ~index-email_attachment-email~:
   - ~account_id~
   - ~email_id~
 
The email attachment can then be fetched at the endpoint `/download/{account_id}/{id}`

**** Asset
Embedded assets are attachments that are used to render the email, rather than meant to be
downloaded as standalone files.

Countrary to email attachments, these are often small, so they're better suited to be stored in
the database.

To avoid duplicating embedded assets (there are lots of duplicated assets, such as corporate
pictures), we store them with their hash, and have an extra join table to link them with the
email.

The ~asset~ table is:
 - ~sha256_hash : Text~, the hash of the asset
 - ~size : Integer~ the byte size of the asset
 - ~data : Blob~, the data itself

Constraints:
 - ~sha256_hash~ primary key

**** JMAP Email has asset
The ~jmap_email_has_asset~ table is:
 - ~account_id : Text~, the account id
 - ~email_id : Text~, the id of the email
 - ~id : Text~ the id of the attachment
 - ~cid : Text?~ the reference of the attachment within the email, to be used like ~<img src="cid:xxxx">~
 - ~asset_hash : Text~, the hash of the asset
 - ~mime_type : Text~ the MIME type of the asset

Constraints:
 - ~(account_id, email_id, id)~ primary key
 - ~(account_id, email_id)~ is a foreign key to ~(accound_id, id)~ in ~jmap_email~
 - ~asset_hash~ is a foreign key to ~sha256_hash~ in ~email_asset~

Indexes:
 - ~index-email_has_asset-email~:
   - ~account_id~
   - ~email_id~
 - ~index-email_has_asset-asset~:
   - ~asset_hash~

~cid~ can be ~NULL~ because JMAP has another way for the email to reference embedded assets, using
URLs.
 
*** FAQ
- Is the ~Message-ID~ header mandatory?

  No, and this header might be abused by spammers or malformed due to outdated mailing systems.
  You have to handle properly missing, malformed or non-unique ~Message-ID~.  However, since
  "normal" mail systems do create unique ~Message-ID~, the UI is allowed to render weirdly messages
  that don't have a unique ~Message-ID~.
- Can the client modify the roles of a directory, in JMAP

  No.  Such a query will result in the server reporting an error.
  
* Code checks
Before pushing a new release, the following checks should be performed
 - License checks.  Run ~cargo deny check licenses~.  This ensure all libraries used are comaptible
   with the license this project is distributed with.
 - Clippy checks.  Run ~cargo clippy~.  This catches common gotchas.
 - Formatting checks.  Run ~cargo fmt --check~.  This ensures the code is written in a normalized
   fashion, avoiding meaningless modifications when your editor tries to format code differently
   than it is.
